---

- name: add docker apt key
  sudo: yes
  apt_key: data="{{ lookup('file', 'docker.key') }}" state=present

- name: add docker apt repository
  sudo: yes
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: install docker
  sudo: yes
  apt: pkg=lxc-docker update_cache=true state=latest

- name: add current user to docker group
  sudo: yes
  user: name={{ ansible_ssh_user }} groups=docker append=yes

- name: create docker config directory
  sudo: yes
  file: path="/etc/systemd/system/docker.service.d" state=directory

- name: set docker config options
  sudo: yes
  template: src="docker.conf.j2" dest=/etc/systemd/system/docker.service.d/docker.conf
  notify:
    - reload systemd
    - restart docker
